# Configuracion inicial de Sandra Server
# @author Code Epic Technologies
# Un archivo .ini es una extensión de archivo para denotar ficheros 
# de configuración utilizados por aplicaciones de los sistemas

[globals]
# este proceso esta asociado a escalabilidad
# possible values : server, client
app_mode = server
# activar crontab al iniciar seguna las funciones 
crontab = true
# activar servicio de php 
server_php = true
# activar servidor de desarrollo
server_dev = true
# activar servidor http
server_http = true
# activar servidor https
server_https = true
# activar servidor de WEB PUSH con rethinkdb
server_push = true
# pool de conexiones IP
# ejemplo de conexiones 192.168.0.10 192.168.0.11 
pool_conection = 127.0.0.1
# permite establecer otra ruta de donde se guardan los log
other_paths = false 
# activar el baner de Sandra Server
banner = false
# activar firmas dinamica rsa de seguridad publica y privada
rsa_signature = true 
# tiempo de bloqueo en minutos despues de varios intentos fallidos
tiempo_bloqueo = 15
# activar la conexion gRPC para el motor de calculos
sentinel_connection = true
# codigo de certificado de 32 digitos para encriptar la contraseña UUID
cert_code = "dd17a4b17e60f28cc11d052a3c82556c"
# Activar la red distribuida de servidores Sandra
federation = true
# Clave secreta compartida para firma de tokens entre nodos
federation_secret = "sandra_distributed_network_secret_2026"

[paths]
#Origen de ruta de la app
base = /usr/local/bin/sandra
# carpeta de log
log = /usr/local/bin/sandra/log 
# Base de archivos para clonar o subir proyectos de terceros
file = /usr/local/bin/sandra/file
# archivos y marcas temporales de QR, TXT, PDF e imangenes
temp = /usr/local/bin/sandra/tmp
# Certificados para los puertos https .key y .cert
signature = /usr/local/bin/sandra/signature
# carpeta donde se alojan las herramientas tools de sandra server
# sandra_dwn, sandra_tcp, sandra_cli, sandra_scanf
bin = /usr/local/bin/sandra/bin

[log]
#g uardar regitro de error, warning e info
system_log = true
# guardar registro de consultas y peticiones
cache_log = true
# guardar registro de consultas SQL
query_log = true
#Regla del cront para realizar respaldo de los log
backup_log = 59 11 * * 5 
# Formato para crear los backuop tgz]zip|tg.xz"
format_log = zip

[server]
# Protocolo (http or https) padre de los servicios
protocol = https
# denificion del servidor 
name_dns = localhost


[hosts]
# host virtuales para sandra
# subdominio.dominio = ruta de la carpeta del proyecto
src.localhost = public_web/src

consola.localhost = public_web/consola

carlos.localhost = public_web/consola

gdoc.localhost = public_web/www/gdoc


# Puertos seguros incluye una firma de certificado y llave 
# que son autorizados por el proveedor de SSL 
[ports]
# servidor principal production
http_app = 80

# puerto https de seguridad usado como marca inicial del proceso
https_app = 443
https_app_cert = signature/sandra.app.crt
https_app_key = signature/sandra.app.key

# puerto para comunicaciones Websocket Chat
https_chat = 8443
https_chat_cert = signature/sandra.app.crt
https_chat_key = signature/sandra.app.key

# puerto https de seguridad
https_dev = 2004
https_dev_cert = signature/sandra.app.crt
https_dev_key = signature/sandra.app.key

# PHP es un proceso experimental de implementacion bajo CGI para 
# compilar clases, archivos o funciones de pho 7, 8+ que se deseen 
# retutilizar como complemento o funciones dentro de las RDN Reglas de negocio
sentinel_port = 50051

[php]
# Puerto de ejecucion de php
php_port = 8087
# Apunta a la version php  y su codigo fuente php.h
php_include = /usr/include 
# Orgien del CGI de php
php_cgi = /opt/homebrew/Cellar/php@8.3/8.3.14/bin/php
# Directorio de origen de PHP
php_dir = /Users/anonymus/Desktop/sandra/public_web/www


# Es una herramienta de ayuda para invocar los drivers o libreras
# que se van a implementar dentro de las diferentes conexiones
[suport]
# Soporte para base de datos MongoDB | MYSQL | POSTGRES | ORACLE
mongodb = true
# Activar soporte para driver de conexion para mysql
mysql = true
# Activar soporte para driver de conexion para postgresql
postgresql = true
# Activar soporte para driver de conexion para oracle
oracle = false

[nomina]
host_nomina = http://localhost:8082/nomina/index.php/WServer/

# Activar servicios de Asistente AI y RethinkDB
# estos servicios son opcionales y pueden ser desactivados segun las necesidades
[assistant]
host_ai = http://localhost:11434
host_rethinkdb = localhost:28015

[federation_nodes]
# Mapeo de nodos: nombre = url
slave = https://192.168.1.126:443
bunker = https://bunker.code-epic.com
cloud = https://cloud.sandra-server.io
epic = https://code-epic.com

